# Generated by Django 4.2.11 on 2024-04-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_borrowrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='----', upload_to='books/'),
            preserve_default=False,
        ),
    ]
