# Generated by Django 4.2.11 on 2024-04-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_borrowrecords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowRecords',
        ),
    ]
